source=~/.config/hypr/colors/hyprlock-colors.conf

background {
    monitor =
    path = $background_image
    blur_passes = 1
    blur_size = 7
    noise = 1.17e-2
    contrast = 0.8916
    brightness = 0.8172s
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

shape {
    monitor =
    size = 310, 360                  
    color =  $entry_background_color
    rounding = 15                  
    border_size = 1
    border_color = $entry_border_color    
    position = 0, 0                  # Centered as the primary foundation card
    halign = center
    valign = center
}

image {
    monitor =
 #   path = /home/omer/Pictures/gowall/3.jpeg

    border_color = $entry_border_color    
    border_size = 2
    size = 100
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd =
    
    position = 0, 95                # Relative offset upward from card center
    halign = center
    valign = center
}

label {
    monitor =
    text = ようこそ
    color = $text_color
    font_size = 16                  # Slightly reduced size to balance the box limits
    font_family = JetBrainsMono Nerd Font Bold
    
    position = 0, 15                 # Relative offset sitting between photo and input
    halign = center
    valign = center
}
input-field {
    monitor =
    size = 250, 40                   # Balanced aspect ratio for modern sizing
    outline_thickness = 1
    dots_size = 0.25 
    dots_spacing = 0.3 
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.1)
    inner_color = rgba(20, 20, 30, 0.5) # Clean input area contrast
    font_color = rgb(240, 240, 240)
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font 
    placeholder_text = <i><span foreground="##ffffff77">Enter Pass</span></i>
    hide_input = false
    
    position = 0, -65                # Positioned relative to card center base
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M %p")</span>"
    color = $entry_color
    font_size = 40
    font_family = JetBrainsMono Nerd Font Bold
    position = 50, -40
    halign = left
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %d %B")"
   
    color = $entry_color
    font_size = 16
    font_family = JetBrainsMono Nerd Font 
    position = 50, -120
    halign = left
    valign = top
}

label {
    text = cmd[update:30000] echo "󰁹 $(cat /sys/class/power_supply/BAT0/capacity)%"
    font_size = 25
    font_family = JetBrainsMono Nerd Font
    color = rgba(255, 255, 255, 0.7)
    position = -50, -50
    halign = right
    valign = top
}

